### PR TITLE
raise error instead of print

### PR DESCRIPTION
**Pull request by hamelsmu**
Two changes:

- Raise an error if it occurs, instead of printing the error
- Print the name of the destination file created

### CODE REVIEW

**Comment by sgugger** [comment]
No, we don't want the conversion to stop if there is an error (which raising an exception will do). We still want the other notebooks to be converted.

**Comment by hamelsmu** [comment]
@sgugger shall I make an option available to raise an error, with the default being to print as it was before - or just revert that part of it completely?

**Comment by sgugger** [comment]
Not sure what's your use case, as errors don't play nicely with parallelism. Do you use only one worker with this?

**Comment by sgugger** [comment]
In that case, I would use the same thing we do in `nbdev_test`: return True if no error and False if there is an error (on top of printing it) in `_notebook2html`, then raise an exception in `notebook2html` if there was one error at least, after the whole conversion has been done.

I can do this in a couple of hours.

**Comment by sgugger** [comment]
Did it in [this commit](https://github.com/fastai/nbdev/commit/54e0723511ee423f5a8aa69722502e002998bb47) so closing this PR.

**Pull request closed without merging**
