### PR TITLE
fixes #1213

### LINKED ISSUE #1213: if `nb_path` contains a space in between, `nbdev_export` fails
Hey @seeM, the recent fix for #1211, the logic breaks again if the `nb_path` contains a whitespace in it. 

I was able to get the docs to render once, I removed the whitespace.
Here's the example,

```python
(base) devengqc@17-CN0065CL-1:~/git/projects/notebooks$ nbdev_prepare
Traceback (most recent call last):
  File "/home/devengqc/git/public/nbdev/nbdev/doclinks.py", line 52, in _iter_py_cells
    try: nb,idx = top.split()
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devengqc/mambaforge/bin/nbdev_prepare", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_prepare')())
  File "/home/devengqc/mambaforge/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/devengqc/git/public/nbdev/nbdev/quarto.py", line 237, in prepare
    nbdev_export.__wrapped__()
  File "/home/devengqc/git/public/nbdev/nbdev/doclinks.py", line 139, in nbdev_export
    _build_modidx()
  File "/home/devengqc/git/public/nbdev/nbdev/doclinks.py", line 101, in _build_modidx
    res['syms'].update(_get_modidx((dest.parent/file).resolve(), code_root, nbs_path=nbs_path))
  File "/home/devengqc/git/public/nbdev/nbdev/doclinks.py", line 72, in _get_modidx
    for cell in _iter_py_cells(py_path):
  File "/home/devengqc/git/public/nbdev/nbdev/doclinks.py", line 54, in _iter_py_cells
    raise NotImplementedError(f"Unexpected format in '{p}' at cell:\n```\n# %% {cell.strip()}.\n```\n"
NotImplementedError: Unexpected format in '/home/devengqc/git/projects/notebooks/notebooks/citygml.py' at cell:

# %% ../nbs/Martin County/citygml_exploration_JS.ipynb 3
from pathlib import Path
from fastcore.script import *
import pandas as pd
from fastcore.foundation import *
from fastcore.xtras import globtastic.

The expected format is: '# %% {nb_path} {cell_idx}'.
```

The `nb_path` contains `Martin County` which I think causes it to break. 

If I replace `Martin County` with `Martin_County` things start working again.

### PR DESCRIPTION
**Pull request by deven-gqc**
This PR tries to fix #1213, if the nb_path contains whitespaces, the code should not break.

### CODE REVIEW

**Comment by deven-gqc** [comment]
@seeM Can you take a look at this?

**Comment by seeM** [comment]
Thanks for this! I'd like to hear @jph00 and @hamelsmu's thoughts before merging.

I think I prefer quoting quoting in the long-term (e.g. `# %% "nb with spaces" 0`) since its more immediately obvious to readers that the group of words represent a single param (vs the proposed syntax `# %% nb with spaces 0`). That said, this is such a convenient (and clever!) fix and I don't see any downsides to it, so maybe we should merge it for now anyway?

**Comment by hamelsmu** [comment]
I agree with quoting; I would be thrown off/ confused by the lack of quotes potentially and would interpret it as positional argument or parameters.

**Comment by hamelsmu** [comment]
I think merging is ok since it unblocks stuff and we can do a follow-on PR if we like to add quotes

**Comment by jph00** [comment]
If we do merge it, let's fix the quotes issue immediately in a followup PR. (We need to consider things like embedded quotes, backslashes, etc too)

**Pull request merged**
