### PR TITLE
Pin Jupyter client version to avoid coroutine error 

### LINKED ISSUE #454: I cannot get pip nbdev working; coroutine was never awaited
To reproduce:
```bash
conda create --name=nbdev_bug python=3.8
conda activate nbdev_bug
pip install nbdev
nbdev_test_nbs
```
returns
```
[...]
RuntimeWarning: coroutine 'ZMQSocketChannel.get_msg' was never awaited
  return False,time.time()-start
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
Test run on the `nbs` folder of this repository.

### PR DESCRIPTION
**Pull request by hamelsmu**
Pin Jupyter client at prior version to fix #454 #456 temporarily.  

We probably need to figure out a long-term solution, however.  cc: @jph00

### CODE REVIEW

**Comment by hamelsmu** [comment]
@kai-tub good idea, thanks

**Comment by kai-tub** [comment]
I was just worried that it would break some databases with older requirements.

**Comment by talosiot-will** [comment]
Any merit to `jupyter-client<=6.1.12` ?

**Comment by hamelsmu** [comment]
@kai-tub no problem, thanks for letting me know!

**Comment by hamelsmu** [comment]
https://github.com/fastai/nbdev/pull/458

**Pull request merged**
