### PR TITLE
add collapse alias with hyphen

### PR DESCRIPTION
**Pull request by hamelsmu**
I found people were making mistakes in adding this option by often using a hyphen instead of underscore, so adding this minor change

### CODE REVIEW

**Comment by sgugger** [comment]
One other thing you could consider is checking the cell metada for 'collapsed: True' (if cell output is toggled with o, this is added).

**Comment by hamelsmu** [comment]
> One other thing you could consider is checking the cell metada for 'collapsed: True' (if cell output is toggled with o, this is added).

Thanks, Sylvian, just so I understand are you thinking about the Collapse Heading or Hide Cells Jupyter plugin?  I know the hide cells plugin is already used by nbdev.

The Collapse Heading is an interesting idea.  Any suggestions on the smoothest user interface to enable/disable this kind of thing?  I have been thinking about it haven't come up with a good idea yet.  

Please let me know your thoughts.  Thanks

**Comment by sgugger** [comment]
I think it comes with collapse headings. Like I said, it adds some metadata in the cell, so if you check for it you can have collapsed outputs be treated directly.

**Comment by hamelsmu** [comment]
Okay, thanks I will look into this soon

**Pull request merged**
