### PR TITLE
Patch for VSCode problem 

### PR DESCRIPTION
**Pull request by HDavidEspinosa**
Hello

In response to the following Issue report: [notebook2script fails on notebooks saved by VS Code native editor #505](https://github.com/fastai/nbdev/issues/505), I have checked the 00_export notebook to try to patch the problem. 

As noted in the commit history, I think the solution is:
Added lines 6 and 7 to check_re function to avoid vscode transformation problem.
Added test after notebook2script cell. The test seems to indicate that the vscode
problem should be fixed.

Since making the changes in this branch I have managed to work with vscode again. 

As noted in the following [comment](https://github.com/fastai/nbdev/issues/505#issuecomment-884068801), the problem is that the new vscode editor adds \r\n characters to new lines. At least in windows. 

The patch, makes sure that all \r\n are simple \n characters before applying the regex.

I also added a test to check this issue has been solved. However, I suspect that github might replace the characters on push. In any case, I uploaded the test notebook in a zip in the afford mentioned issue.

I hope this helps others I love nbdev and hope it sticks around for a long while.

### CODE REVIEW

**Comment by jph00** [comment]
Many thanks @HDavidEspinosa . I'm not able to merge this directly, since it's got a lot of unrelated changes across 21 files. Instead I'll just make the edit directly, if that's OK.

Many thanks for looking into this issue.

**Comment by HDavidEspinosa** [comment]
Sounds great cheers.

**Comment by HDavidEspinosa** [comment]
@jph00 sorry to keep bugging with this issue.

Today I reviewed the solution and found that, though it works, it also introduces a problem. In notebooks with \r\n the built modules end up with double  \n which can break some modules. 

The better solution is to make two changes to the export module. 
in the check_re function  the last three lines should be:
    cell_source = cell['source'].replace('\r', '') # Eliminates the \r\n bug
    result = pat.search(cell_source)
    return result

The second change is to the split_flags_and_code function, there the first line of the function can be replaced for:
    source_str = cell['source'].replace('\r', '')
    code_lines = source_str.split('\n')
instead of 
    code_lines = cell['source'].replace('\n')

This works fine. Thanks again

**Comment by jph00** [comment]
@HDavidEspinosa please don't apologize for helping! :) Thanks for your suggestion - I've added that now.

**Pull request closed without merging**
