### PR TITLE
fix _re_image and add callbacks

### PR DESCRIPTION
**Pull request by pete88b**
Few little things
- Fixed `_re_image` so that we can use ( in captions. [see forum](https://forums.fast.ai/t/nbdev-fastpages-how-to-insert-images-side-by-side/73500)
- Removed `_re_image1` as it's not used anywhere
- Changed test to not call `notebook2script` - like we already did for docs

... and one slightly bigger change
- I've added callbacks to build docs and test nbs

Hopefully 09_nbdev_callback_test.ipynb explains why I think nbdev needs this - but the short version is; wouldn't it be great if we could solve problems like [not being able to get code coverage](https://forums.fast.ai/t/nbdev-code-coverage-n-tests/73993) and [having to zero indent img tags](https://forums.fast.ai/t/nbdev-fastpages-how-to-insert-images-side-by-side/73500/5) without changing nbdev code?

Would you like me to make a PR to update docs? I think we need to update the sidebar and a few other little things.

Hope this all helps,

Pete

### CODE REVIEW

**Comment by pete88b** [comment]
Just realized that fastai2 used callback names like "begin_test_nb"/"after_test_nb".

Let me know if you'd like me to change "on_test_nb_begin"/"on_test_nb_end" to follow this convention.

**Comment by jph00** [comment]
Sorry for the delay in looking at this. Yes please do rename the callbacks - thanks!

**Comment by pete88b** [comment]
I've renamed the callbacks - this one is ready to go.

I'll try to take a look at `__future__` imports this week too

**Comment by jph00** [comment]
Great!

**Pull request merged**
