### PR TITLE
Remove export-other from directives doc

### PR DESCRIPTION
**Pull request by hugetim**
See #742

### CODE REVIEW

**Comment by hugetim** [comment]
@jph00 , I made this quick pull request to make the docs consistent with the current functionality for now while we decide whether/how to implement the `#|export <other.module>` directive.

**Comment by jph00** [comment]
Many thanks!

**Comment by fgiasson** [comment]
Is there a place where this discussion is taking place? I faced that issue just now. It seems it was working with v1, but not anymore. Actually, it "kind" of work if:

 1. I create a new notebook with `default_exp foo`
 2. export one cell to default
 3. export one cell to `bar` 
 4. create `module/foo.py` manually
 5. create `module/bar.py` manually
 6. define `__all__` manually in `module/bar.py`
 7. run `nbdev_export` from the command line

Except for the manual process incurred, the exported cell(s) in `bar.py` are appended (instead of replaced) after each call of `nbdev_export` (but this duplication is not happening in `foo.py`, which uses the default export directive.

I haven't checked the code yet, but I would be interested to follow the conversation around that question from the maintenance team.

**Comment by hugetim** [comment]
> Is there a place where this discussion is taking place? ...

This issue seems the proper place: https://github.com/fastai/nbdev/issues/742

**Pull request merged**
