### PR TITLE
fixes #1405

### LINKED ISSUE #1405: Blog post broken links
In this blog post: https://nbdev.fast.ai/blog/posts/2022-08-25-jupyter-git/

The broken link near the top:

> To get started, follow the directions on [Git-friendly Jupyter](https://nbdev.fast.ai/01_Tutorials/02_git_friendly_jupyter.html) 

Probably means to point to this link: https://nbdev.fast.ai/tutorials/git_friendly_jupyter.html

### PR DESCRIPTION
**Pull request by deven367**
This PR fixes the broken link in the `jupyter-git` blog.

### CODE REVIEW

**Comment by deven367** [comment]
Hi @jph00, I'm not sure why runners are failing, I think GH has internally removed the Intel-based runners for `macos`? I may be wrong? Any thoughts?

**Comment by jph00** [comment]
Ah looks like 3.7 isn't supported any more. I just removed it. Can you merge in my change from master?

**Comment by deven367** [comment]
@jph00 I just merged from the master. 

In a different PR, should I also remove 3.7 from the `py_versions?`
https://github.com/fastai/nbdev/blob/153f2f6a6b55a29b295affbf8d9dd9844d66a169/setup.py#L29

**Comment by jph00** [comment]
Many thanks. I don't think we need to update setup.py since the lib still works fine -- it's just not in CI.

**Pull request merged**
