### PR TITLE
`show_doc` treats functions decorated with `lru_cache` as classes

### PR DESCRIPTION
**Pull request by seeM**
@hamelsmu @jph00, not sure if this is a good solution?

### CODE REVIEW

**Comment by seeM** [comment]
Maybe a better solution is to use `sym.__wrapped__` if it exists

**Comment by seeM** [comment]
Just realised `show_doc` also isn't showing a param table for these functions

**Comment by jph00** [comment]
In general I suspect we should be using `__wrapped__` when it's available.

**Comment by jph00** [comment]
I've just changed it to use `__wrapped__` instead - seems to work OK.

**Pull request closed without merging**
