### PR TITLE
Update jekyll.tpl

### PR DESCRIPTION
**Pull request by hamelsmu**
This closes https://github.com/fastai/nbdev/issues/106

### CODE REVIEW

**Comment by hamelsmu** [comment]
@sgugger I can open a separate PR, the original purpose of these raw tags were to escape liquid in notebooks which were causing things to break, especially in code cells.  

I can make a separate PR if you wish to target code cells only, this fixes the problem for now

**Comment by sgugger** [comment]
Escaping them in code cells sounds fine to me, if you don't mind doing a separate PR. Ideally it would be nice to know what things are broken so we escape those specifically.

**Comment by hamelsmu** [comment]
The things that are broken is when people try to put `{{` in their code, which for example is common if someone is using Keras  callbacks to format stuff.  I don't think there is any way around it except to escape the code block for liquid

**Comment by sgugger** [comment]
Ok, so the fix sounds right then.

**Pull request merged**
