### PR TITLE
add support for 3.11 

### LINKED ISSUE #1372: In settings.ini `min_python = 3.11` causes problem with pip install -e '.[dev]'
Traceback:

```
pip install -e '.[dev]'
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [9 lines of output]

setup.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "setup.py", line 40, in <module>
          ] + ['Programming Language :: Python :: '+o for o in py_versions[py_versions.index(min_python):]] + (['License :: ' + lic[1] ] if lic[1] else []),
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ValueError: '3.11' is not in list
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

### PR DESCRIPTION
**Pull request by deven367**
hello, I'm trying to add support for py3.11 for `nbdev`, I'm trying some stuff on my fork. The PR will also eventually close #1372. 

I had a question for @jph00, there's only one test case which fails for 3.11 which is in `showdoc`. This has only come into existence because the docstring for the Enum was changed in 3.11. How should I try to handle the test case in such a situation? The test case is listed below,

```py
AssertionError                            Traceback (most recent call last)
Cell In[1], line 2
      1 e = enum.Enum('e', 'a b')
----> 2 test_eq(str(show_doc(e)), '---\n\n### e\n\n>      e (value, names=None, module=None, qualname=None, type=None, start=1)\n\nAn enumeration.')

File ~/mambaforge/envs/fun/lib/python3.11/site-packages/fastcore/test.py:37, in test_eq(a, b)
     35 def test_eq(a,b):
     36     "`test` that `a==b`"
---> 37     test(a,b,equals, cname='==')

File ~/mambaforge/envs/fun/lib/python3.11/site-packages/fastcore/test.py:27, in test(a, b, cmp, cname)
     25 "`assert` that `cmp(a,b)`; display inputs and `cname or cmp.__name__` if it fails"
     26 if cname is None: cname=cmp.__name__
---> 27 assert cmp(a,b),f"{cname}:\n{a}\n{b}"

AssertionError: ==:
---

### e

>      e (value, names=None, module=None, qualname=None, type=None, start=1,
>         boundary=None)

Create a collection of name/value pairs.

Example enumeration:

>>> class Color(Enum):
...     RED = 1
...     BLUE = 2
...     GREEN = 3

Access them by:

- attribute access::

>>> Color.RED
<Color.RED: 1>

- value lookup:

>>> Color(1)
<Color.RED: 1>

- name lookup:

>>> Color['RED']
<Color.RED: 1>

Enumerations can be iterated over, and know how many members they have:

>>> len(Color)
3

>>> list(Color)
[<Color.RED: 1>, <Color.BLUE: 2>, <Color.GREEN: 3>]

Methods can be added to enumerations, and members can have their own
attributes -- see the documentation for details.
---

### e

>      e (value, names=None, module=None, qualname=None, type=None, start=1)

An enumeration.

```

### CODE REVIEW

**Comment by deven367** [comment]
I think even that won't be possible. They've changed the entire docstring and they've even added a new arg (`boundary=None`) to the Enum class.

```py
# new in 3.11
e (value, names=None, module=None, qualname=None, type=None, start=1, boundary=None)
Create a collection of name/value pairs.

# in previous versions
e (value, names=None, module=None, qualname=None, type=None, start=1)
An enumeration.
```

**Comment by deven367** [comment]
Will do!

**Comment by deven367** [comment]
@jph00 It's ready for review.

**Comment by jph00** [comment]
Thank you!

**Pull request merged**
