### PR TITLE
Allow option to create a GitHub release

### PR DESCRIPTION
**Pull request by fabge**
Currently there is the possibility of creating PyPI and conda releases. Would it be of interested to create a release in GitHub as well?
I didn't find existing functionality and assumed you do this manually currently?

### CODE REVIEW

**Comment by hamelsmu** [comment]
Really sorry I pressed merge on the wrong PR!

**Comment by hamelsmu** [comment]
Do you mind reopening this PR please.  Sorry about this

**Comment by jph00** [comment]
@fabge thanks for the very neat PR! We actually have something for this already though, which is our fastai/fastrelease project. But your PR has inspired me to merge it into nbdev, so please watch this space :)

**Comment by fabge** [comment]
Thank you very much, I will definitely watch it closely. The work from all of you is incredibly inspiring and teaches me a lot!

**Comment by jph00** [comment]
Here you go @fabge https://nbdev.fast.ai/release.html

**Pull request merged**
