### PR TITLE
fixes #1364

### LINKED ISSUE #1364: nbdev_help doesn't explain what the command nbdev_readme is
## Provide a minimally reproducible example

1.  Install the latest version of nbdev
2. Run `nbdev_help`

```
nbdev_bump_version        Increment version in settings.ini by one
nbdev_changelog           Create a CHANGELOG.md file from closed and labeled GitHub issues
nbdev_clean               Clean all notebooks in `fname` to avoid merge conflicts
nbdev_conda               Create a `meta.yaml` file ready to be built into a package, and optionally build and upload it
nbdev_create_config       Create a config file.
nbdev_docs                Create Quarto docs and README.md
nbdev_export              Export notebooks in `path` to Python modules
nbdev_filter              A notebook filter for Quarto
nbdev_fix                 Create working notebook from conflicted notebook `nbname`
nbdev_help                Show help for all console scripts
nbdev_install             Install Quarto and the current library
nbdev_install_hooks       Install Jupyter and git hooks to automatically clean, trust, and fix merge conflicts in notebooks
nbdev_install_quarto      Install latest Quarto on macOS or Linux, prints instructions for Windows
nbdev_merge               Git merge driver for notebooks
nbdev_migrate             Convert all markdown and notebook files in `path` from v1 to v2
nbdev_new                 Create an nbdev project.
nbdev_prepare             Export, test, and clean notebooks, and render README if needed
nbdev_preview             Preview docs locally
nbdev_proc_nbs            Process notebooks in `path` for docs rendering
nbdev_pypi                Create and upload Python package to PyPI
nbdev_readme              None
nbdev_release_both        Release both conda and PyPI packages
nbdev_release_gh          Calls `nbdev_changelog`, lets you edit the result, then pushes to git and calls `nbdev_release_git`
nbdev_release_git         Tag and create a release in GitHub for the current version
nbdev_sidebar             Create sidebar.yml
nbdev_test                Test in parallel notebooks matching `path`, passing along `flags`
nbdev_trust               Trust notebooks matching `fname`
nbdev_update              Propagate change in modules matching `fname` to notebooks that created them
```

## Expected behaviour

nbdev_readme - should be saying it updates README.md file based on index.qmd

### PR DESCRIPTION
**Pull request by deven367**
This PR adds a minor docstring for `nbdev_readme`. cc @jph00

### CODE REVIEW

**Comment by hugetim** [comment]
The docstring is not accurate in the case that the `readme_nb` config option is set to something other than 'index.ipynb'. 
How about just: "Create README.md" 
Or else "Create README.md from readme_nb (index.ipynb by default)"?

**Comment by jph00** [comment]
I like : Create README.md from readme_nb (index.ipynb by default)

**Comment by deven367** [comment]
Thanks @hugetim, I've revised the docstring.

**Comment by hugetim** [comment]
Oops, it looks like the notebook metadata needs cleaning up.

**Review by hugetim — APPROVED** [review]
Thank you!

**Comment by jph00** [comment]
Thanks! :D

**Comment by jph00** [comment]
Thanks :D

**Pull request merged**
