### PR TITLE
Fixed typos in README.md

### PR DESCRIPTION
**Pull request by joe-bender**
Fixed simple typos in README.md, including repeated words, wrong words, wrong file names, wrong capitalization, and missing closing parentheses.

### CODE REVIEW

**Comment by muellerzr** [comment]
You should make this fix in index.ipynb. This is what the readme is generated from, and your fixes will be lost if we build the docs again. (This goes for any of the fastai repos that utilize nbdev as well)

**Comment by joe-bender** [comment]
Oops. I'll fix that. Should I close this and make a new PR?

**Comment by muellerzr** [comment]
No, just commit to your fork the adjustment (also don’t run nbdev_build_docs, Jeremy will do this).

**Comment by joe-bender** [comment]
Is there a way to just take the second commit and not the first? I'm not sure how to remove that first commit.

**Comment by joe-bender** [comment]
I guess it wouldn't hurt to also include the README changes.

**Comment by jph00** [comment]
Looks like we have some conflicts - do you mind fixing them please?

**Comment by joe-bender** [comment]
I'm really having trouble rebasing. I will try to figure this out.

**Comment by joe-bender** [comment]
Ok, I just did it on github.

**Comment by jph00** [comment]
Thanks for the fixes!

**Pull request merged**
